name: MinePlugin
version: ${project.version}
main: org.example.MinePlugin
api-version: "1.21"          # version reconnue par Spigot/Paper

commands:
  army:
    description: Fait apparaître 5 loups + 2 golems
    usage: /army
  ping:
    description: Répond « Pong ! »
    usage: /ping
  mineur:
    description: Gestion du mineur automatisé
    usage: |
      /mineur wand
      /mineur create
      /mineur speed <slow|normal|fast>
      /mineur pattern <quarry|branch|tunnel|vein_first>
      /mineur pause|resume|stop|info|trust <joueur>
    permission: mineplugin.mineur.use
  champ:
    description: Crée un champ automatisé (labour, plantation, récolte)
    usage: /champ [Largeur]x[Longueur]
  foret:
    description: Crée une forêt automatisée (plantation et récolte d’arbres)
    usage: /foret [Largeur]x[Longueur]
  village:
    description: Génère un petit village de PNJ
    usage: /village
  eleveur:
    description: Crée un enclos automatisé pour l'élevage
    usage: /eleveur
  armure:
    description: Donne l'Armure du roi GIDON
    usage: /armure
  marchand:
    description: Invoque un marchand PNJ personnalisé
    usage: /marchand
    permission: mineplugin.marchand.spawn
  minegus:
    description: Outils d'administration MineGus
    usage: /minegus fix <forestier|golems>
    permission: mineplugin.admin
  job:
    description: Gestion des métiers (mineur, etc.)
    usage: |
      /job mineur
      /job info

permissions:
  mineplugin.mineur.use:
    description: Utiliser les fonctionnalités du mineur automatisé
    default: true
  mineplugin.mineur.admin:
    description: Administrer toutes les sessions du mineur
    default: op
  mineplugin.marchand.spawn:
    description: Invoquer ou recharger le marchand
    default: op
  mineplugin.admin:
    description: Accéder aux commandes d'administration MineGus
    default: op

softdepend:
  - WorldGuard
  - GriefPrevention
  - Lands
